version: '3.8'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: 'webpacker'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3030:3000"
    user: "1000:1000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    user: "1000:1000"
  db:
    image: postgres:latest
    ports:
      - "5442:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'adminpass'
volumes:
  db-volume:
  bundle:
